apiVersion: v1
kind: PersistentVolume
metadata:
  name: crm-${ENVIRONMENT}-redis-data
spec:
  storageClassName: crm-${ENVIRONMENT}-redis-data
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/crm/${ENVIRONMENT}/redis/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
           - key: kubernetes.io/hostname
             operator: In
             values:
              - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crm-${ENVIRONMENT}-redis-log
spec:
  storageClassName: crm-${ENVIRONMENT}-redis-log
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/crm/${ENVIRONMENT}/redis/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
           - key: kubernetes.io/hostname
             operator: In
             values:
              - minikube
          
